apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-buergerbuero
  name: ms-buergerbuero
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-buergerbuero
    spec:
      containers:
      - image: postgres
        name: ms-buergerbuero-db
        env:
        - name: POSTGRES_DB
          value: "buergerbuero"
        - name: POSTGRES_USER
          value: "sgse-ss2020"
        - name: POSTGRES_PASSWORD
          value: "buergerbuero"
        ports:
        - containerPort: 5432
      - image: ms-buergerbuero-frontend
        name: ms-buergerbuero-frontend
        ports:
        - containerPort: 80
      - image: ms-buergerbuero-backend
        name: ms-buergerbuero-backend
        ports:
        - containerPort: 8080
        - containerPort: 50051
      restartPolicy: Always
status: {}
